# Generated by Django 2.0.1 on 2018-02-10 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep04', '0002_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',)},
        ),
    ]
